[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_soroban_bridge = "9inMRAuig1bbuLXbLXTEpTG4Km5aCU3DctamwhjH5fQ5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dell/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
