[features]
seeds = false
skip-lint = false
[programs.devnet]
sorolan_bridge = "iJwTrtis4FHdPmqgGpE8qH5XrbhN6SRpYD5xiX8cEf2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
