[features]
seeds = false
skip-lint = false
[programs.localnet]
sorolan_bridge = "5w7LLcjXEwmzh3W8yhsxZxrPx6Xo83pa69kSf4mRZAUp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/imentus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
