[features]
seeds = false
skip-lint = false
[programs.devnet]
sorolan_bridge = "8zRhmZnnpyCTkunFPb6LVSxeh7fyCZ9wH5xGPwu68Trb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
