[features]
seeds = false
skip-lint = false
[programs.devnet]
sorolan_bridge = "HADg73vhw376PgZ7UcVU25s7ag8aidbBf1ZLB41d6EC7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
