[features]
seeds = false
skip-lint = false
[programs.devnet]
sorolan_bridge = "7mq4zw63J2cABg3g37UxJx9eq5oErtmRVDEjtTCbUU8a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/imentus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
