[features]
seeds = false
skip-lint = false
[programs.devnet]
sorolan_bridge = "EjBudpF98VVNGiSdkDEatKeeT8S6uxRWYzV6kRFcxmhY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
